apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales

    spec:
      terminationGracePeriodSeconds: 60

#      initContainers:
#      - name: init-migrate-seed
#        image: service-image
#        command: ['./sales-admin', 'migrate-seed']
#        env:
#        - name: SALES_DB_USER
#          valueFrom:
#            configMapKeyRef:
#              name: app-config
#              key: db_user
#              optional: true
#        - name: SALES_DB_PASSWORD
#          valueFrom:
#            configMapKeyRef:
#              name: app-config
#              key: db_password
#              optional: true
#        - name: SALES_DB_HOST_PORT
#          valueFrom:
#            configMapKeyRef:
#              name: app-config
#              key: db_hostport
#              optional: true
#        - name: SALES_DB_DISABLE_TLS
#          valueFrom:
#            configMapKeyRef:
#              name: app-config
#              key: db_disabletls
#              optional: true

      containers:
      - name: sales-api
        image: service-image